version: "3"
services:
  ocreniisan:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - ARCH=x86_64
    container_name: app-ocreniisan
    volumes:
      - type: bind
        source: "./"
        target: "/app"
    environment:
      TZ: '${TIME_ZONE}'
      GOOGLE_APPLICATION_CREDENTIALS: '${GOOGLE_APPLICATION_CREDENTIALS}'
    ports:
      - "8004:8004"
    restart: always
