services:
  ocreniisan:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ocreniisan
    container_name: ocreniisan
    volumes:
      - type: bind
        source: "./"
        target: "/app"
    environment:
      TZ: '${TIME_ZONE}'
      GOOGLE_APPLICATION_CREDENTIALS: '${GOOGLE_APPLICATION_CREDENTIALS}'
    ports:
      - "8004:8004"
    restart: always
